### ISSUE TITLE
Kmeans_and_gms - wrong code at Computation Time

### ISSUE THREAD

**Issue by nguyenbh1507** [KacperKubara/ml-cookbook#1]
When I look at the graph and the following lines of code:

```# Measure time for different number of clusters
for i in range(1, 11):
  kmeans = KMeans(n_clusters=3,...)
  gm = GaussianMixture(n_components=3,...)
  gm_kmeans = GaussianMixture(n_components=3, ...)
```

I think it should be `n_clusters=i` for K-Means and `n_components=i` for GMM

Another problem is time for GMM is always 0 because of
```
  gm.fit_predict(data_new)
  start_gm = time.time()
  stop_gm = time.time()
```
`start_gm` and `start_gm` are the same !!!

**Comment by KacperKubara** [comment]
Hey @nguyenbh1507 , thanks for spotting that. Perhaps when I was cleaning up the Jupyter notebook to put it into the repo, I forgot to modify that. I will change it and double run it to confirm that results are as in the article.

**Comment by KacperKubara** [comment]
Fix is already in the colab, I will close the issue then
